## Tarea final
### Hugo Villanueva
### Postgrado en análisis y predicción de Datos


In [6]:
import numpy as np
import matplotlib.pyplot as plt


**Ejercicio**: Investigar y ejemplificar diferencias entre np.array y np.matrix

La diferencia consiste que mientras **np.array** es un método para crear arreglos de tensores de cualquier rango, **np.matrix** es especializado en tensores de rango 2. Es decir np.matrix es un método para construir matrices. 

Ejemplo en la construción de un tensor de rango 3 se utiliza especificamente np.array

In [18]:
tensor3 = np.array([[[2,3],[2,5]],[[2,3],[2,5]]])

array([[[2, 3],
        [2, 5]],

       [[2, 3],
        [2, 5]]])

Por otro lado con np.matrix se tiene:

In [22]:
matriz = np.matrix([[5,2],[2,3]])

Se podría considerar la anterior matriz mediante un arreglo de np.array

In [20]:
matriz_1 = np.array([[5,2],[2,3]])

Pero al aplicar operaciones y métodos distintos en ambas concepciones, encontramos.
**Elevar cuadrado**

In [23]:
print(matriz**2)
print(matriz_1**2)

[[29 16]
 [16 13]]
[[25  4]
 [ 4  9]]


En la primera se encuentra el producto de matrices convencional en el álgebra lineal, mientras que en el segundo se eleva componente a componente al cuadrado, (producto hadamard)

In [30]:
print(matriz.I)
print(matriz_1.I)

[[ 0.27272727 -0.18181818]
 [-0.18181818  0.45454545]]


AttributeError: 'numpy.ndarray' object has no attribute 'I'

Fuente de consulta https://www.semicolonworld.com/question/43342/what-are-the-differences-between-numpy-arrays-and-matrices-which-one-should-i-use

### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [7]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

In [15]:
H1_W = np.array([[0.25,-8],
                 [0.37,14]])
OL_W = np.array([[4],[9]])

X =  np.array([[0.1,0.2],
               [1,2]])

H1 = np.matmul(X,H1_W)
H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
OL = np.matmul(H1,OL_W)
OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1


print(OL)

[[0.99995577]
 [0.99999332]]


In [50]:
#Implementando la red neuronal
X = np.array([[1,1]])
def neural_net(X,f):
    H1_W = np.array([[0.712, 0.355, 0.268], [0.112, 0.855, 0.468]])
    H1 = sigmoid(np.matmul(X, H1_W))
    OL_W = np.array([0.116, 0.329, 0.708])
    OL = f(np.matmul(H1, OL_W))
    return OL
neural_net(X,sigmoid)

array([0.69269553])

In [71]:
def ReLu(X):
    ans = np.max(np.array(X),axis=0)
    return ans
print(ReLu(X))

neural_net(X, ReLu)

[1 1]


0.8127515352804022